CREATE TABLE IF NOT EXISTS product (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    brand VARCHAR(255) NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    category VARCHAR(255) NOT NULL,
    release_date DATE,
    product_available BOOLEAN NOT NULL,
    stock_quantity INTEGER NOT NULL,
    image_name VARCHAR(255),
    image_type VARCHAR(255),
    image_url VARCHAR(500),
    search_vector TSVECTOR GENERATED ALWAYS AS (
        to_tsvector(
            'english',
            coalesce(name, '') || ' ' ||
            coalesce(brand, '') || ' ' ||
            coalesce(category, '') || ' ' ||
            coalesce(description, '')
        )
    ) STORED,
    CONSTRAINT chk_product_price_non_negative CHECK (price >= 0),
    CONSTRAINT chk_product_stock_non_negative CHECK (stock_quantity >= 0)
);

CREATE INDEX IF NOT EXISTS idx_product_search_vector
    ON product USING GIN (search_vector);

CREATE INDEX IF NOT EXISTS idx_product_category
    ON product (category);

CREATE INDEX IF NOT EXISTS idx_product_available
    ON product (product_available);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255),
    provider VARCHAR(50) NOT NULL DEFAULT 'LOCAL',
    role VARCHAR(50) NOT NULL DEFAULT 'USER',
    CONSTRAINT chk_users_provider CHECK (provider IN ('LOCAL', 'GOOGLE')),
    CONSTRAINT chk_users_role CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT chk_local_user_has_password CHECK (
        provider <> 'LOCAL' OR password IS NOT NULL
    )
);

CREATE INDEX IF NOT EXISTS idx_users_email
    ON users (email);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id VARCHAR(255) NOT NULL UNIQUE,
    customer_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    mobile_no VARCHAR(10) NOT NULL,
    status VARCHAR(50) NOT NULL,
    order_date DATE NOT NULL,
    user_email VARCHAR(255) NOT NULL,
    CONSTRAINT chk_orders_status CHECK (status IN ('PLACED', 'CANCELLED')),
    CONSTRAINT chk_orders_mobile_no CHECK (mobile_no ~ '^[6-9][0-9]{9}$')
);

CREATE INDEX IF NOT EXISTS idx_orders_user_email
    ON orders (user_email);

CREATE INDEX IF NOT EXISTS idx_orders_order_date
    ON orders (order_date);

CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    total_price NUMERIC(12, 2) NOT NULL,
    order_id BIGINT NOT NULL,
    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id)
        REFERENCES product (id),
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
        REFERENCES orders (id)
        ON DELETE CASCADE,
    CONSTRAINT chk_order_items_quantity_positive CHECK (quantity > 0),
    CONSTRAINT chk_order_items_total_price_non_negative CHECK (total_price >= 0)
);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id
    ON order_items (order_id);

CREATE INDEX IF NOT EXISTS idx_order_items_product_id
    ON order_items (product_id);

CREATE TABLE IF NOT EXISTS wishlist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email VARCHAR(255) NOT NULL,
    product_id INTEGER NOT NULL,
    CONSTRAINT fk_wishlist_items_product
        FOREIGN KEY (product_id)
        REFERENCES product (id)
        ON DELETE CASCADE,
    CONSTRAINT uk_wishlist_user_product
        UNIQUE (user_email, product_id)
);

CREATE INDEX IF NOT EXISTS idx_wishlist_items_user_email
    ON wishlist_items (user_email);

CREATE INDEX IF NOT EXISTS idx_wishlist_items_product_id
    ON wishlist_items (product_id);
